"""
alpha/batch_generator.py
-------------------------
Massively Parallel Factor Generation — Stage 1: Batch Formula Generation.

Generates large batches of syntactically-valid, deduplicated formula
strings. Four generation strategies combine to cover the search space:

  TEMPLATE_EXPANSION  — cartesian product of operators × features
                         ~200 formulas in <1ms, guaranteed valid
  HYPOTHESIS_GUIDED   — seeds from HypothesisEvolution, then mutations
                         focuses search on high-confidence idea regions
  RANDOM_EVOLUTION    — random formulas via AlphaEvolution._random_formula
                         maintains diversity, avoids local optima
  LIBRARY_CROSSOVER   — crossover of existing high-IC library formulas
                         exploits what already works

All four strategies run and their outputs are merged, deduplicated
(SHA-256 hash), and shuffled before returning.

Deduplication key: SHA-256 hash of stripped formula string.
A formula submitted by any miner or generated by any strategy is
stored in a global seen set so it is never evaluated twice.

Usage
-----
    prices = load_market_data(...)
    gen    = BatchFormulaGenerator(hypothesis_lib, formula_lib)

    batch  = gen.generate(n=1000)
    # batch: list of up to 1000 unique formula strings

    # For hypothesis-guided generation:
    batch  = gen.generate(n=500, strategy="hypothesis_guided")
"""

from __future__ import annotations

import hashlib
import random
import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional

_SUBNET = Path(__file__).resolve().parent.parent
_ROOT   = _SUBNET.parent
for p in [str(_SUBNET), str(_ROOT)]:
    if p not in sys.path:
        sys.path.insert(0, p)

from macro8_subnet.alpha.formula_engine     import FormulaEngine
from macro8_subnet.alpha.hypothesis_engine  import HypothesisLibrary, HypothesisEvolution


# ── Constants ─────────────────────────────────────────────────────────────────

FEATURES = [
    "momentum_5d", "momentum_10d", "momentum_20d", "momentum_60d",
    "volatility_10d", "volatility_20d", "volatility_60d",
    "zscore_20d", "zscore_60d",
    "rsi_14",
    "cross_momentum", "relative_vol", "regime_signal",
]

UNARY_OPS = ["zscore", "rank", "neutralize", "sign", "abs"]
DECAY_PARAMS = [(5, "halflife"), (10, "halflife"), (20, "halflife")]
ARITHMETIC   = ["+", "-"]


class GenerationStrategy(str, Enum):
    TEMPLATE_EXPANSION = "template"
    HYPOTHESIS_GUIDED  = "hypothesis"
    RANDOM_EVOLUTION   = "random"
    LIBRARY_CROSSOVER  = "crossover"
    MIXED              = "mixed"


# ── Result ────────────────────────────────────────────────────────────────────

@dataclass
class BatchGenerationReport:
    """Summary of one batch generation run."""
    n_requested:      int
    n_generated:      int
    n_deduplicated:   int
    n_invalid:        int
    strategy_counts:  dict[str, int]
    elapsed_ms:       float

    def to_dict(self) -> dict:
        return {
            "n_requested":    self.n_requested,
            "n_generated":    self.n_generated,
            "n_deduplicated": self.n_deduplicated,
            "n_invalid":      self.n_invalid,
            "strategy_counts": self.strategy_counts,
            "elapsed_ms":     round(self.elapsed_ms, 2),
            "throughput":     round(self.n_generated / max(self.elapsed_ms/1000, 1e-6), 0),
        }


# ── Batch Generator ───────────────────────────────────────────────────────────

class BatchFormulaGenerator:
    """
    High-throughput formula batch generator for MPFG.

    Combines four strategies to cover both breadth (template expansion)
    and depth (hypothesis-guided search) of the formula space.

    The generator is stateful: it maintains a global seen-set across
    calls so the same formula is never returned twice in a session.
    Call reset_seen() to start a fresh exploration.
    """

    def __init__(
        self,
        hypothesis_library: Optional[HypothesisLibrary] = None,
        formula_library     = None,   # FormulaLibrary (optional, for crossover)
        feature_store       = None,   # FeatureStore (optional, for engine)
        seed:               int  = 42,
    ):
        self._hyp_lib      = hypothesis_library
        self._form_lib     = formula_library
        self._rng          = random.Random(seed)
        self._seen:        set[str] = set()    # global dedup set

        # Validation engine (optional — skip validation if no feature store)
        if feature_store is not None:
            self._engine = FormulaEngine(feature_store)
        else:
            self._engine = None

        # Hypothesis evolution helper
        if hypothesis_library is not None:
            self._hyp_evo = HypothesisEvolution(hypothesis_library)
        else:
            self._hyp_evo = None

    # ── Public API ────────────────────────────────────────────────────────────

    def generate(
        self,
        n:        int                   = 1000,
        strategy: GenerationStrategy    = GenerationStrategy.MIXED,
    ) -> list[str]:
        """
        Generate up to N unique, valid formula strings.

        Args:
            n:        Target number of formulas to generate.
            strategy: Generation strategy (MIXED recommended).

        Returns:
            List of at most N formula strings, deduplicated across all
            previous calls in this session.
        """
        import time
        t0      = time.perf_counter()

        if strategy == GenerationStrategy.MIXED:
            candidates = self._mixed_strategy(n * 3)  # over-generate then trim
        elif strategy == GenerationStrategy.TEMPLATE_EXPANSION:
            candidates = self._template_expansion()
        elif strategy == GenerationStrategy.HYPOTHESIS_GUIDED:
            candidates = self._hypothesis_guided(n * 2)
        elif strategy == GenerationStrategy.RANDOM_EVOLUTION:
            candidates = self._random_evolution(n * 2)
        elif strategy == GenerationStrategy.LIBRARY_CROSSOVER:
            candidates = self._library_crossover(n * 2)
        else:
            candidates = self._template_expansion()

        # Deduplicate and validate
        unique   = []
        n_dup    = 0
        n_inv    = 0

        for formula in candidates:
            fhash = self._hash(formula)
            if fhash in self._seen:
                n_dup += 1
                continue
            if self._engine is not None:
                ok, _ = self._engine.validate_formula(formula)
                if not ok:
                    n_inv += 1
                    continue
            else:
                # Basic syntactic check without engine
                if not formula.strip() or len(formula) > 200:
                    n_inv += 1
                    continue
            self._seen.add(fhash)
            unique.append(formula)
            if len(unique) >= n:
                break

        elapsed_ms = (time.perf_counter() - t0) * 1000

        # Store last report for inspection
        self._last_report = BatchGenerationReport(
            n_requested=n,
            n_generated=len(unique),
            n_deduplicated=n_dup,
            n_invalid=n_inv,
            strategy_counts={"mixed": len(unique)},
            elapsed_ms=elapsed_ms,
        )

        return unique

    def generate_with_report(
        self,
        n:        int                 = 1000,
        strategy: GenerationStrategy  = GenerationStrategy.MIXED,
    ) -> tuple[list[str], BatchGenerationReport]:
        """Generate formulas and return both the list and the report."""
        formulas = self.generate(n, strategy)
        return formulas, self._last_report

    def reset_seen(self) -> None:
        """Clear the deduplication history — allows re-exploring formulas."""
        self._seen.clear()

    @property
    def n_seen(self) -> int:
        return len(self._seen)

    # ── Strategy implementations ──────────────────────────────────────────────

    def _template_expansion(self) -> list[str]:
        """
        Cartesian product of operators × features → guaranteed valid formulas.
        Generates ~200-300 formulas in <1ms.
        """
        formulas = []

        # Single feature (baseline)
        formulas.extend(FEATURES)

        # Unary operator × feature
        for op in UNARY_OPS:
            for feat in FEATURES:
                formulas.append(f"{op}({feat})")

        # Decay × feature
        for feat in FEATURES:
            for n, kw in DECAY_PARAMS:
                formulas.append(f"decay({feat}, {kw}={n})")

        # Rank difference pairs (most powerful class)
        for i, f1 in enumerate(FEATURES):
            for f2 in FEATURES[i+1:]:
                formulas.append(f"rank({f1}) - rank({f2})")

        # Lag × feature
        for feat in FEATURES[:6]:   # limit to avoid explosion
            for lag in [1, 2, 5]:
                formulas.append(f"lag({feat}, n={lag})")

        # Zscore difference
        for f1 in FEATURES[:5]:
            for f2 in FEATURES[5:10]:
                formulas.append(f"zscore({f1}) - zscore({f2})")

        self._rng.shuffle(formulas)
        return formulas

    def _hypothesis_guided(self, n: int) -> list[str]:
        """
        Generate formulas guided by hypothesis engine confidence scores.
        High-confidence hypotheses → more formulas in their feature space.
        """
        formulas = []

        # Seed from hypothesis evolution
        if self._hyp_evo is not None:
            seeds    = self._hyp_evo.seed_formulas(min(20, n // 10))
            formulas.extend(seeds)

            # Mutate seeds to expand
            suggested = self._hyp_evo.suggested_features()
            if suggested:
                biased_features = list(set(suggested + FEATURES[:5]))
                for _ in range(n - len(formulas)):
                    f1 = self._rng.choice(biased_features)
                    f2 = self._rng.choice(biased_features)
                    op = self._rng.choice(UNARY_OPS)
                    roll = self._rng.random()
                    if roll < 0.4:
                        formulas.append(f"rank({f1}) - rank({f2})")
                    elif roll < 0.7:
                        formulas.append(f"{op}({f1})")
                    else:
                        formulas.append(f"decay({f1}, halflife={self._rng.choice([5,10,20])})")

        # Fall back to template if no hypothesis library
        if not formulas:
            formulas = self._template_expansion()

        return formulas[:n]

    def _random_evolution(self, n: int) -> list[str]:
        """Random formula generation via AlphaEvolution-style random walk."""
        from macro8_subnet.alpha.alpha_evolution import AlphaEvolution

        class _FakeFS:
            def get(self, name):
                return None

        evo      = AlphaEvolution(_FakeFS(), population_size=1, seed=self._rng.randint(0, 9999))
        formulas = []
        attempts = 0

        while len(formulas) < n and attempts < n * 5:
            attempts += 1
            f = evo._random_formula()
            if f and len(f) < 100:
                formulas.append(f)

        return formulas

    def _library_crossover(self, n: int) -> list[str]:
        """
        Crossover of existing high-IC library formulas.
        Only available when formula_library is provided.
        """
        if self._form_lib is None:
            return self._template_expansion()

        top_formulas = [r.formula_string
                        for r in self._form_lib.rank_by_ic(20)]

        if not top_formulas:
            return self._template_expansion()

        from macro8_subnet.alpha.alpha_evolution import AlphaEvolution

        class _FakeFS:
            def get(self, name):
                return None

        evo      = AlphaEvolution(_FakeFS(), population_size=1, seed=42)
        formulas = []

        for _ in range(n):
            a = self._rng.choice(top_formulas)
            b = self._rng.choice(top_formulas)
            if a != b:
                formulas.append(evo._crossover(a, b))
            else:
                formulas.append(evo._mutate(a))

        return formulas

    def _mixed_strategy(self, n: int) -> list[str]:
        """
        Blend of all four strategies weighted by expected diversity.
        Template: 30%  (breadth, guaranteed valid)
        Hypothesis: 30% (guided depth)
        Random: 25%    (diversity)
        Crossover: 15% (exploitation)
        """
        quarter = n // 4
        pool    = []
        pool.extend(self._template_expansion())
        pool.extend(self._hypothesis_guided(quarter))
        pool.extend(self._random_evolution(quarter))
        pool.extend(self._library_crossover(quarter // 2))
        self._rng.shuffle(pool)
        return pool

    @staticmethod
    def _hash(formula: str) -> str:
        return hashlib.sha256(formula.strip().encode()).hexdigest()[:16]
